# Generated by Django 6.0.5 on 2026-09-06 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artists/profile/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='artists/banners/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('apple_music_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('followers_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='music_artis_name_e97718_idx'), models.Index(fields=['is_active', 'name'], name='music_artis_is_acti_a71a06_idx'), models.Index(fields=['is_verified', 'name'], name='music_artis_is_veri_da4ffd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('release_type', models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('mixtape', 'Mixtape'), ('compilation', 'Compilation'), ('other', 'Other')], default='album', max_length=20)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='albums/artwork/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('editorial_review', models.TextField(blank=True)),
                ('editorial_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('apple_music_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('audiomack_url', models.URLField(blank=True)),
                ('boomplay_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('favorites_count', models.PositiveBigIntegerField(default=0)),
                ('ratings_count', models.PositiveBigIntegerField(default=0)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_albums', to=settings.AUTH_USER_MODEL)),
                ('artists', models.ManyToManyField(related_name='albums', to='music.artist')),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='music.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=5000)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('likes_count', models.PositiveBigIntegerField(default=0)),
                ('comments_count', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden'), ('removed', 'Removed')], default='published', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=3000)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('likes_count', models.PositiveBigIntegerField(default=0)),
                ('replies_count', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden'), ('removed', 'Removed')], default='published', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='music.communitypostcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music.communitypostcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPostCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate Speech'), ('sexual', 'Sexual Content'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='music.communitypostcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate Speech'), ('sexual', 'Sexual Content'), ('misinformation', 'Misinformation'), ('copyright', 'Copyright'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='music.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=330, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('likes_count', models.PositiveBigIntegerField(default=0)),
                ('comments_count', models.PositiveBigIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_articles', to='music.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_articles', to='music.artist')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editorial_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music.editorialarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_article_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialArticleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate Speech'), ('sexual', 'Sexual Content'), ('misinformation', 'Misinformation'), ('copyright', 'Copyright'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='music.editorialarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_article_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=3000)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('likes_count', models.PositiveBigIntegerField(default=0)),
                ('replies_count', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden'), ('removed', 'Removed')], default='published', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.editorialarticle')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='music.editorialcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music.editorialcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate Speech'), ('sexual', 'Sexual Content'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='music.editorialcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='music_genre_is_acti_1d7647_idx')],
            },
        ),
        migrations.AddField(
            model_name='editorialarticle',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='editorial_articles', to='music.genre'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='songs/artwork/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('editorial_review', models.TextField(blank=True)),
                ('editorial_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('production_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('lyrics_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('vocals_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('replay_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('cultural_impact_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('apple_music_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('audiomack_url', models.URLField(blank=True)),
                ('boomplay_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('favorites_count', models.PositiveBigIntegerField(default=0)),
                ('ratings_count', models.PositiveBigIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.album')),
                ('artists', models.ManyToManyField(related_name='songs', to='music.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_songs', to='music.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='songs', to='music.genre')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='editorialarticle',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_articles', to='music.song'),
        ),
        migrations.CreateModel(
            name='CommunityPostTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('song', 'Song'), ('album', 'Album'), ('artist', 'Artist'), ('external', 'External')], max_length=20)),
                ('external_provider', models.CharField(blank=True, choices=[('itunes', 'iTunes / Apple Music'), ('spotify', 'Spotify'), ('musicbrainz', 'MusicBrainz'), ('other', 'Other')], max_length=30)),
                ('external_content_type', models.CharField(blank=True, choices=[('song', 'Song'), ('album', 'Album'), ('artist', 'Artist')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('artist_name', models.CharField(blank=True, max_length=500)),
                ('album_name', models.CharField(blank=True, max_length=300)),
                ('artwork_url', models.URLField(blank=True, max_length=1000)),
                ('preview_url', models.URLField(blank=True, max_length=1000)),
                ('spotify_url', models.URLField(blank=True, max_length=1000)),
                ('apple_music_url', models.URLField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_post_targets', to='music.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_post_targets', to='music.artist')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='music.communitypost')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_post_targets', to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracklist', to='music.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_track_entries', to='music.song')),
            ],
            options={
                'ordering': ['track_number'],
            },
        ),
        migrations.CreateModel(
            name='SongFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='music.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['album', '-created_at'], name='music_album_album_i_c1f5ab_idx'), models.Index(fields=['user', '-created_at'], name='music_album_user_id_b8ba7a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'album'), name='unique_user_album_favorite')],
            },
        ),
        migrations.CreateModel(
            name='AlbumRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['album', '-created_at'], name='music_album_album_i_68ee0d_idx'), models.Index(fields=['user', '-created_at'], name='music_album_user_id_e7479e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'album'), name='unique_user_album_rating'), models.CheckConstraint(condition=models.Q(('rating__in', [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0])), name='album_rating_half_star')],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['status', '-release_date'], name='music_album_status_e73879_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['is_featured', '-release_date'], name='music_album_is_feat_ddfdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_type', 'status'], name='music_album_release_7e83cd_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['status', '-published_at'], name='music_album_status_ed5146_idx'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(('status', 'published'), _negated=True), _connector='OR'), name='album_published_requires_date'),
        ),
        migrations.AddIndex(
            model_name='artistfollow',
            index=models.Index(fields=['artist', '-created_at'], name='music_artis_artist__94f0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='artistfollow',
            index=models.Index(fields=['user', '-created_at'], name='music_artis_user_id_f2f014_idx'),
        ),
        migrations.AddConstraint(
            model_name='artistfollow',
            constraint=models.UniqueConstraint(fields=('user', 'artist'), name='unique_user_artist_follow'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['user', '-created_at'], name='music_commu_user_id_ce4346_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['status', '-created_at'], name='music_commu_status_3a7cf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypost',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), ('rating__in', [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]), _connector='OR'), name='community_post_half_star_rating'),
        ),
        migrations.AddIndex(
            model_name='communitypostcomment',
            index=models.Index(fields=['post', 'parent', 'status', 'created_at'], name='music_commu_post_id_eac12d_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostcomment',
            index=models.Index(fields=['parent', 'status', 'created_at'], name='music_commu_parent__b58092_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostcomment',
            index=models.Index(fields=['user', '-created_at'], name='music_commu_user_id_61d94f_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostcommentlike',
            index=models.Index(fields=['comment', '-created_at'], name='music_commu_comment_d847f2_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostcommentlike',
            index=models.Index(fields=['user', '-created_at'], name='music_commu_user_id_8b853c_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypostcommentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_community_comment_like'),
        ),
        migrations.AddIndex(
            model_name='communitypostcommentreport',
            index=models.Index(fields=['comment', '-created_at'], name='music_commu_comment_7472e6_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostcommentreport',
            index=models.Index(fields=['reason', '-created_at'], name='music_commu_reason_3cf7c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypostcommentreport',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_community_comment_report'),
        ),
        migrations.AddIndex(
            model_name='communitypostlike',
            index=models.Index(fields=['post', '-created_at'], name='music_commu_post_id_2146b4_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostlike',
            index=models.Index(fields=['user', '-created_at'], name='music_commu_user_id_692e20_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypostlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_like'),
        ),
        migrations.AddIndex(
            model_name='communitypostreport',
            index=models.Index(fields=['post', '-created_at'], name='music_commu_post_id_80757d_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostreport',
            index=models.Index(fields=['reason', '-created_at'], name='music_commu_reason_5143c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypostreport',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_report'),
        ),
        migrations.AddIndex(
            model_name='editorialarticlelike',
            index=models.Index(fields=['article', '-created_at'], name='music_edito_article_fe75cd_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialarticlelike',
            index=models.Index(fields=['user', '-created_at'], name='music_edito_user_id_ae3100_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialarticlelike',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_like'),
        ),
        migrations.AddIndex(
            model_name='editorialarticlereport',
            index=models.Index(fields=['article', '-created_at'], name='music_edito_article_f64a54_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialarticlereport',
            index=models.Index(fields=['reason', '-created_at'], name='music_edito_reason_ce8ed4_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialarticlereport',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_report'),
        ),
        migrations.AddIndex(
            model_name='editorialcomment',
            index=models.Index(fields=['article', 'parent', 'status', 'created_at'], name='music_edito_article_e5a6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialcomment',
            index=models.Index(fields=['parent', 'status', 'created_at'], name='music_edito_parent__7d0128_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialcomment',
            index=models.Index(fields=['user', '-created_at'], name='music_edito_user_id_ccad8a_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialcommentlike',
            index=models.Index(fields=['comment', '-created_at'], name='music_edito_comment_6e6c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialcommentlike',
            index=models.Index(fields=['user', '-created_at'], name='music_edito_user_id_93198c_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialcommentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_editorial_comment_like'),
        ),
        migrations.AddIndex(
            model_name='editorialcommentreport',
            index=models.Index(fields=['comment', '-created_at'], name='music_edito_comment_e468ac_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialcommentreport',
            index=models.Index(fields=['reason', '-created_at'], name='music_edito_reason_6113d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialcommentreport',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_editorial_comment_report'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['status', '-release_date'], name='music_song_status_59c3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_featured', '-release_date'], name='music_song_is_feat_c4268c_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album', 'status'], name='music_song_album_i_c370f0_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['status', '-published_at'], name='music_song_status_fc1bd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(('status', 'published'), _negated=True), _connector='OR'), name='song_published_requires_date'),
        ),
        migrations.AddIndex(
            model_name='editorialarticle',
            index=models.Index(fields=['status', '-published_at'], name='music_edito_status_80f909_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialarticle',
            index=models.Index(fields=['author', '-created_at'], name='music_edito_author__b1d7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialarticle',
            index=models.Index(fields=['song', 'status'], name='music_edito_song_id_0d166a_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialarticle',
            index=models.Index(fields=['artist', 'status'], name='music_edito_artist__79deb6_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialarticle',
            index=models.Index(fields=['album', 'status'], name='music_edito_album_i_022f3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialarticle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(('status', 'published'), _negated=True), _connector='OR'), name='article_published_requires_date'),
        ),
        migrations.AddIndex(
            model_name='communityposttarget',
            index=models.Index(fields=['target_type'], name='music_commu_target__8b2544_idx'),
        ),
        migrations.AddIndex(
            model_name='communityposttarget',
            index=models.Index(fields=['external_provider', 'external_content_type', 'external_id'], name='music_commu_externa_8fc668_idx'),
        ),
        migrations.AddIndex(
            model_name='communityposttarget',
            index=models.Index(fields=['external_provider', 'external_id'], name='music_commu_externa_aebdff_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityposttarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('album__isnull', True), ('artist__isnull', True), ('external_content_type', ''), ('external_id', ''), ('external_provider', ''), ('song__isnull', False), ('target_type', 'song')), models.Q(('album__isnull', False), ('artist__isnull', True), ('external_content_type', ''), ('external_id', ''), ('external_provider', ''), ('song__isnull', True), ('target_type', 'album')), models.Q(('album__isnull', True), ('artist__isnull', False), ('external_content_type', ''), ('external_id', ''), ('external_provider', ''), ('song__isnull', True), ('target_type', 'artist')), models.Q(('album__isnull', True), ('artist__isnull', True), ('external_content_type__gt', ''), ('external_id__gt', ''), ('external_provider__gt', ''), ('song__isnull', True), ('target_type', 'external'), ('title__gt', '')), _connector='OR'), name='valid_community_post_target'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='unique_album_track_number'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='unique_song_per_album'),
        ),
        migrations.AddIndex(
            model_name='songfavorite',
            index=models.Index(fields=['song', '-created_at'], name='music_songf_song_id_660e34_idx'),
        ),
        migrations.AddIndex(
            model_name='songfavorite',
            index=models.Index(fields=['user', '-created_at'], name='music_songf_user_id_40cc33_idx'),
        ),
        migrations.AddConstraint(
            model_name='songfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'song'), name='unique_user_song_favorite'),
        ),
        migrations.AddIndex(
            model_name='songrating',
            index=models.Index(fields=['song', '-created_at'], name='music_songr_song_id_96367f_idx'),
        ),
        migrations.AddIndex(
            model_name='songrating',
            index=models.Index(fields=['user', '-created_at'], name='music_songr_user_id_ccd499_idx'),
        ),
        migrations.AddConstraint(
            model_name='songrating',
            constraint=models.UniqueConstraint(fields=('user', 'song'), name='unique_user_song_rating'),
        ),
        migrations.AddConstraint(
            model_name='songrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__in', [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0])), name='song_rating_half_star'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower', '-created_at'], name='music_userf_followe_707517_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['following', '-created_at'], name='music_userf_followi_85ec7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_user_follow'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='prevent_self_follow'),
        ),
    ]
