# Generated by Django 5.2.5 on 2025-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='genre',
            new_name='group',
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
