# Generated by Django 5.2.5 on 2025-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_genre_song_group_song_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dj',
            name='genres',
            field=models.CharField(blank=True, default='Mixtape', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
