# Generated by Django 5.2.5 on 2025-09-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_genre_alter_dj_genres_alter_song_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='rating_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
