# Generated by Django 5.2.5 on 2025-09-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(to='music.tag'),
        ),
    ]
