# Generated by Django 5.2.5 on 2025-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
