# Generated by Django 5.2.5 on 2025-10-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='album_covers/')),
                ('release_date', models.DateField()),
                ('artists', models.ManyToManyField(related_name='albums', to='music.artist')),
            ],
        ),
        migrations.DeleteModel(
            name='Lyrics',
        ),
    ]
