# Generated by Django 5.2.5 on 2025-10-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_delete_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
