# Generated by Django 5.2.5 on 2025-10-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artists',
            new_name='artist',
        ),
    ]
