# Generated by Django 5.2.5 on 2025-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_rename_artists_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='group',
            field=models.CharField(default='Album'),
        ),
    ]
