# Generated by Django 5.2.7 on 2025-10-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_rename_body_comment_comment_alter_comment_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
