# Generated by Django 5.2.7 on 2025-10-12 22:23

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_rename_comment_comment_body'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
