# Generated by Django 5.2.7 on 2025-10-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_song_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_cover',
            field=models.ImageField(blank=True, null=True, upload_to='temp_covers/'),
        ),
    ]
