# Generated by Django 5.2.7 on 2025-10-15 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_song_original_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_views', to='music.song')),
            ],
        ),
    ]
