# Generated by Django 5.2.7 on 2025-10-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_songview'),
    ]

    operations = [
        migrations.AddField(
            model_name='songview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
