# Generated by Django 5.2.7 on 2025-10-26 02:03

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_songview_ip_address_alter_songview_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='songs', to='music.artist'),
        ),
    ]
