# Generated by Django 5.2.7 on 2025-10-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_alter_song_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='dj_file',
            field=models.FileField(default='', upload_to='mixtapes/'),
            preserve_default=False,
        ),
    ]
