# Generated by Django 5.2.7 on 2025-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_dj_dj_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='group',
            field=models.CharField(default='Mixtape', max_length=10),
        ),
    ]
