# Generated by Django 5.2.7 on 2025-10-28 22:00

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_dj_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='artists',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='mixtapes', to='music.artist'),
        ),
    ]
