# Generated by Django 5.2.7 on 2025-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_dj_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='djs', to='music.comment'),
        ),
    ]
