# Generated by Django 5.2.7 on 2025-10-29 00:41

from django.db import migrations

def add_sort_value_column(apps, schema_editor):
    # This will add the missing column for SortedManyToManyField
    schema_editor.execute(
        'ALTER TABLE music_song_artists ADD COLUMN sort_value integer DEFAULT 0'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_remove_comment_song_comment_content_type_and_more'),
    ]

    operations = [
        migrations.RunPython(add_sort_value_column),
    ]
