# Generated by Django 5.2.7 on 2025-10-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_add_sort_value_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='genres',
            new_name='genre',
        ),
    ]
