# Generated by Django 5.2.7 on 2025-10-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_rename_genres_dj_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='cover',
            new_name='dj_cover',
        ),
    ]
