# Generated by Django 5.2.7 on 2025-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_rename_cover_dj_dj_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='comments',
        ),
        migrations.AlterField(
            model_name='song',
            name='group',
            field=models.CharField(blank=True, default='Music', max_length=50, null=True),
        ),
    ]
