# Generated by Django 5.2.7 on 2025-10-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_remove_dj_comments_alter_song_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
