# Generated by Django 5.2.7 on 2025-10-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
