# Generated by Django 5.2.7 on 2026-02-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_musiccomment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccomment',
            name='dj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.dj'),
        ),
        migrations.AlterField(
            model_name='songview',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='songview',
            unique_together={('song', 'ip_address')},
        ),
    ]
