# Generated by Django 5.2.7 on 2026-02-07 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0037_musiccomment_dj_alter_songview_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccomment',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.song'),
        ),
    ]
