# Generated by Django 5.2.7 on 2026-02-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_alter_musiccomment_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='name',
            new_name='dj_name',
        ),
        migrations.AlterField(
            model_name='dj',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
