# Generated by Django 6.0.4 on 2026-04-15 09:08

import taggit_autosuggest.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0039_rename_name_dj_dj_name_alter_dj_slug'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
