# Generated by Django 6.0.4 on 2026-05-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_alter_category_options_alter_song_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.RemoveField(
            model_name='dj',
            name='category',
        ),
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
