# Generated by Django 6.0.4 on 2026-05-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0041_rename_category_genre_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djs', to='music.genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.genre'),
        ),
    ]
