# Generated by Django 6.0.4 on 2026-05-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0042_dj_category_song_category_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
