# Generated by Django 6.0.4 on 2026-05-12 07:26

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0043_remove_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genres',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='songs', to='music.genre'),
        ),
    ]
