# Generated by Django 6.0.5 on 2026-06-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0045_alter_song_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musiccomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='musiccomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_auth_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
