# Generated by Django 6.0.5 on 2026-06-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0047_ipblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpBlock',
        ),
    ]
