# Generated by Django 6.0.5 on 2026-06-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0048_delete_ipblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='genre',
        ),
    ]
