# Generated by Django 6.0.5 on 2026-06-13 10:26

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0049_remove_dj_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='genre',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='Mix', to='music.genre'),
        ),
    ]
