# Generated by Django 6.0.5 on 2026-06-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0050_dj_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='dj',
            name='category',
        ),
    ]
