# Generated by Django 6.0.5 on 2026-06-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0051_rename_genre_dj_genres_remove_dj_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.RemoveField(
            model_name='song',
            name='group',
        ),
        migrations.RemoveField(
            model_name='song',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='song',
            name='rating_total',
        ),
    ]
