# Generated by Django 6.0.5 on 2026-06-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0052_remove_song_category_remove_song_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='group',
        ),
    ]
