# Generated by Django 6.0.5 on 2026-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0053_remove_dj_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_ative',
            field=models.BooleanField(default=True),
        ),
    ]
