# Generated by Django 6.0.5 on 2026-06-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0054_song_is_ative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_ative',
            new_name='is_active',
        ),
    ]
