# Generated by Django 5.2.7 on 2025-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('trending', 'Trending'), ('lifestyle', 'Lifestyle'), ('technology', 'Technology')], max_length=50)),
                ('thumbnail', models.ImageField(upload_to='news_thumbnails/')),
                ('content', models.TextField()),
                ('author', models.CharField(default='VibeNation', max_length=100)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
