# Generated by Django 5.2.7 on 2025-10-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_options_news_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_blog',
            field=models.BooleanField(default=False),
        ),
    ]
