# Generated by Django 5.2.7 on 2025-10-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_is_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
