# Generated by Django 5.2.7 on 2025-10-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_meta_description_news_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='meta_title',
        ),
    ]
