# Generated by Django 5.2.7 on 2025-10-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
