# Generated by Django 5.2.7 on 2025-10-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_blog',
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='news.news')),
            ],
        ),
    ]
