# Generated by Django 5.2.7 on 2026-01-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_newscomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_published'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
