# Generated by Django 5.2.7 on 2026-03-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
