# Generated by Django 5.2.7 on 2026-03-30 17:37

import taggit_autosuggest.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_news_is_sponsored_news_sponsor_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
