# Generated by Django 5.2.7 on 2026-03-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_news_expired_at_alter_news_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='expired_at',
            new_name='expires_at',
        ),
    ]
