# Generated by Django 6.0.4 on 2026-04-15 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_news_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date to schedule this post.'),
        ),
    ]
