# Generated by Django 6.0.4 on 2026-04-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_news_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
