# Generated by Django 6.0.4 on 2026-04-16 16:07

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_remove_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='news', to='news.category'),
        ),
    ]
