# Generated by Django 6.0.4 on 2026-05-11 00:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_news_category'),
        ('otp_static', '0003_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedStaticDevice',
            fields=[
                ('staticdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_static.staticdevice')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_static.staticdevice',),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='You can set a future date to schedule this post.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Set an expiry date for this sponsored post.', null=True),
        ),
    ]
