# Generated by Django 6.0.4 on 2026-05-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_backupcode_delete_extendedstaticdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupCode',
        ),
    ]
