# Generated by Django 6.0.4 on 2026-05-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_delete_backupcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
    ]
