# Generated by Django 6.0.4 on 2026-05-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_remove_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
