# Generated by Django 6.0.4 on 2026-05-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_alter_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
