# Generated by Django 6.0.5 on 2026-06-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_ipblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipblock',
            options={'verbose_name': 'IpBlock', 'verbose_name_plural': 'Blocked IP Address'},
        ),
    ]
