# Generated by Django 5.2.7 on 2026-03-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('html_code', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adzone')),
            ],
        ),
    ]
