# Generated by Django 5.2.7 on 2026-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='impressions',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
