# Generated by Django 5.2.7 on 2026-03-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_impressions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adzone'),
        ),
    ]
