# Generated by Django 6.0.5 on 2026-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_advertisement_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='adzone',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
