"""
Django settings for vibenation project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
import environ
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from pathlib import Path

env = environ.Env(
    DEBUG=(bool, False)
)

BASE_DIR = Path(__file__).resolve().parent.parent

# Read the .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG') 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CKEditor Configuration
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'jpg', 'png', 'gif', 'webp'] 
CKEDITOR_5_MAX_FILE_SIZE = 5
CKEDITOR_5_IMAGE_CLEANUP = True
TAGGIT_CASE_INSENSITIVE = True 

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 
            'bold', 'italic', 'link', 'underline', 'strikethrough', '|',
            'bulletedList', 'numberedList', 'alignment', '|',
            'imageUpload', 'mediaEmbed', 'insertTable', 'blockQuote', '|',
            'fontSize', 'fontColor', 'fontBackgroundColor', '|',
            'undo', 'redo', 'removeFormat'
        ],
        'mediaEmbed': {'previewsInData': True},
        'alignment': {'options': ['left', 'center', 'right', 'justify']},
        'htmlSupport': {
            'allow': [
                {'name': 'div', 'classes': True, 'attributes': True, 'styles': True},
                {'name': 'script', 'attributes': True}, 
                {'name': 'iframe', 'attributes': True},
                {'name': 'blockquote', 'classes': True}, 
            ]
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight', '|',
                'resizeImage'
            ],
            'styles': ['full', 'alignLeft', 'alignCenter', 'alignRight']
        },
        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Courier New, Courier, monospace',
                'Georgia, serif',
                'Times New Roman, Times, serif',
                'Verdana, Geneva, sans-serif'
            ]
        },
        'fontSize': {'options': ['tiny', 'small', 'default', 'large', 'huge']},
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties'
            ]
        },
    }
}

# ALLOWED_HOSTS using the smart list feature
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters", 
    "unfold.contrib.forms",
    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",

    # Two-Factor Authentication
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',

    # Third Party Plugins
    'django_ckeditor_5',
    'sortedm2m',
    'taggit',
    'taggit_autosuggest',
    'django_cleanup.apps.CleanupConfig',

    # Local Apps
    'news',
    'music',
    'ads',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'vibenation.middleware.IpBlockMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'vibenation.middleware.AdminURLFixerMiddleware',
]

ROOT_URLCONF = 'vibenation.urls'

LOGIN_REDIRECT_URL = '/'

LOGIN_URL = '/vibe-crew-login-2026/login/'

LOGOUT_REDIRECT_URL = None

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vibenation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env.int('DB_PORT', default=5432),
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static",]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =================================
# PRODUCTION & SECURITY SETTINGS
# ================================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Cloudflare R2 Storage Settings
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    # Connect Django's "AWS" variables
    AWS_ACCESS_KEY_ID = env('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env('R2_ENDPOINT_URL')
    AWS_S3_CUSTOM_DOMAIN = env('R2_CUSTOM_DOMAIN')
    
    # R2 Specific settings
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_REGION_NAME = 'auto' # Cloudflare R2 usually uses 'auto'

# Global requirement for Unfold's responsive layout engines
X_FRAME_OPTIONS = 'SAMEORIGIN'
SITE_ID = 1

UNFOLD = {
    "SITE_TITLE": "VibeNation Admin",
    "SITE_HEADER": "VibeNation",
    "SITE_SYMBOL": lambda request: mark_safe(
        f'<img src="{static("images/vibe_cream_favicon.png")}" class="w-10 h-10 object-contain" alt="VN Logo">'
    ),

    "STYLES": [
        lambda request: static("css/unfold_patch.css"),
    ],

    "DASHBOARD_CALLBACK": "vibenation.admin_site.dashboard_stats_callback",

    "TABS": [],
    "SHOW_HISTORY": False,
    "SHOW_VIEW_ON_SITE": False,
    
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Advertisement Management",
                "separator": True,
                "items": [
                    {
                        "title": "Ad Zones",
                        "link": reverse_lazy("admin:ads_adzone_changelist"),
                        "icon": "ads_click",
                        "permission": lambda request: request.user.has_perm("ads.view_adzone")
                    },
                    {
                        "title": "Ads",
                        "link": reverse_lazy("admin:ads_advertisement_changelist"),
                        "icon": "campaign",
                        "permission": lambda request: request.user.has_perm("ads.view_advertisement")
                    },
                ],
            },
            {
                "title": "News Management",
                "separator": True,
                "items": [
                    {
                        "title": "Articles",
                        "link": reverse_lazy("admin:news_news_changelist"),
                        "icon": "article",
                        "permission": lambda r: r.user.has_perm("news.view_news")
                    },
                    {
                        "title": "Categories",
                        "link": reverse_lazy("admin:news_category_changelist"),
                        "icon": "category",
                        "permission": lambda r: r.user.has_perm("news.view_category")
                    },
                    {
                        "title": "News Comments",
                        "link": reverse_lazy("admin:news_newscomment_changelist"),
                        "icon": "comment",
                        "permission": lambda r: r.user.has_perm("news.view_newscomment")
                    },
                ],
            },
            {
                "title": "Music Management",
                "separator": True,
                "items": [
                    {
                        "title": "Songs",
                        "link": reverse_lazy("admin:music_song_changelist"),
                        "icon": "music_note",
                        "permission": lambda r: r.user.has_perm("music.view_song")
                    },
                    {
                        "title": "Artists", 
                        "link": reverse_lazy("admin:music_artist_changelist"), 
                        "icon": "person", 
                        "permission": lambda r: r.user.has_perm("music.view_artist")
                    },
                    {
                        "title": "Albums", 
                        "link": reverse_lazy("admin:music_album_changelist"), 
                        "icon": "album", 
                        "permission": lambda r: r.user.has_perm("music.view_album")
                    },
                    {
                        "title": "DJs", 
                        "link": reverse_lazy("admin:music_dj_changelist"), 
                        "icon": "headphones", 
                        "permission": lambda r: r.user.has_perm("music.view_dj")
                    },
                    {
                        "title": "Music Comments", 
                        "link": reverse_lazy("admin:music_musiccomment_changelist"), 
                        "icon": "forum", 
                        "permission": lambda r: r.user.has_perm("music.view_musiccomment")
                    },
                ],
            },
            {
                "title": "Users & Administration",
                "separator": True,
                "items": [
                    {
                        "title": "Users", 
                        "link": reverse_lazy("admin:auth_user_changelist"), 
                        "icon": "person", 
                        "permission": lambda request: request.user.has_perm("auth.view_user")
                    },
                    {
                        "title": "Groups", 
                        "link": reverse_lazy("admin:auth_group_changelist"), 
                        "icon": "groups", 
                        "permission": lambda request: request.user.has_perm("auth.view_group")
                    },
                    {
                        "title": "Log Entries", 
                        "link": reverse_lazy("admin:admin_logentry_changelist"), 
                        "icon": "history", 
                        "permission": lambda request: request.user.is_superuser
                    },
                ],
            },
            {
                "title": "Security",
                "separator": True,
                "items": [
                    {
                        "title": "Static Devices", 
                        "link": reverse_lazy("admin:otp_static_staticdevice_changelist"), 
                        "icon": "no_encryption", 
                        "permission": lambda request: request.user.is_superuser
                    },
                    {
                        "title": "TOTP Devices",
                        "link": reverse_lazy("admin:otp_totp_totpdevice_changelist"),
                        "icon": "phonelink_lock",
                        "permission": lambda request: request.user.is_superuser
                    },
                    {
                        "title": "Blocked IP Address",
                        "link": reverse_lazy("admin:news_ipblock_changelist"),
                        "icon": "shield",
                        "permission": lambda request: request.user.is_superuser
                    }
                ],
            },
        ],
    },
}